### ISSUE TITLE
如何获取 抽卡查询 API URL？

### ISSUE THREAD

**Issue by Ricardo-Riley** [LittleNyima/honkai-starrail-toolkit#1]
readme中 写道：
获取抽卡查询 API URL
由此可以获得一个形如 https://api-takumi.mihoyo.com/common/gacha_record/api/getGachaLog?xxxxx 的 URL，后续步骤使用的就是这个 URL。注意：API URL 会在一定时间后过期，过期后需要重新获取。

请问一下 由此可以获得  这个由此是哪里？

**Comment by LittleNyima** [comment]
刚刚加上了获得 API URL 的教程，可以参考[这个链接](https://github.com/LittleNyima/honkai-starrail-toolkit/blob/develop/docs/how-to-get-api-url.md)。

**Comment by Ricardo-Riley** [comment]
看完了 但是pc版本 可以有另外一种方法，参考原神抽卡记录项目("https://github.com/sunfkny/genshin-gacha-export")  ,在游戏目录 Star Rail\Game\StarRail_Data\webCaches\Cache\Cache_Data\data_2 文本搜索 https://api-takumi.mihoyo.com/common/gacha_record/api/getGachaLog 查找最后匹配的链接 可以得到url 地址。

**Comment by LittleNyima** [comment]
> 看完了 但是pc版本 可以有另外一种方法，参考原神抽卡记录项目("https://github.com/sunfkny/genshin-gacha-export") ,在游戏目录 Star Rail\Game\StarRail_Data\webCaches\Cache\Cache_Data\data_2 文本搜索 https://api-takumi.mihoyo.com/common/gacha_record/api/getGachaLog 查找最后匹配的链接 可以得到url 地址。

感谢提醒，我在文档里补充一下这个方法。
