### ISSUE TITLE
解锁帧率时报错

### ISSUE THREAD

**Issue by BJY666** [LittleNyima/honkai-starrail-toolkit#12]
如图，想知道如何解决，是否是环境配置的问题？
<img width="719" alt="屏幕截图 2024-09-01 023252" src="https://github.com/user-attachments/assets/63bf9d76-8445-40b8-a63d-e1dafbd93e74">

**Comment by LittleNyima** [comment]
可能是注册表项不存在导致的，可以先尝试在游戏里设置一次帧率，再尝试解锁帧率

**Comment by BJY666** [comment]
您好，感谢回复，在游戏里设置过帧率就可以正常解锁120帧了
