### ISSUE TITLE
导入数据时，对于 UIGF v4.0 所有允许为 string 的 field 请勿强制要求 int。

### ISSUE THREAD

**Issue by ShikiSuen** [LittleNyima/honkai-starrail-toolkit#13]
![bfcaaddf34ff5ff2a070a9b7069e436d](https://github.com/user-attachments/assets/50813453-ae82-4c1d-8ccf-a96581141180)

**Comment by LittleNyima** [comment]
了解，我近期会修改一下这里的逻辑

**Comment by ShikiSuen** [comment]
@LittleNyima 嗯。Python 我不懂，但可以这么干：
用 Regex 检查是否由 0-9 组成、且 field 资料值长度合理（不为空）。

**Comment by LittleNyima** [comment]
已修复
