### ISSUE TITLE
导出的抽卡记录只有前五条

### ISSUE THREAD

**Issue by voidzhakul** [LittleNyima/honkai-starrail-toolkit#2]
抽卡记录是通过参数`end_id`和`size`来检索，而不是通过`page`，你的请求只改动`page`是没用的。你用postman测一下大概就明白我说的什么意思了。

**Comment by LittleNyima** [comment]
感谢反馈，实际上在每次请求之后，`end_id` 是被替换为上次的最后一个 id 的，并不是只改动了 `page`。只有前五条的问题我这里暂时没有遇到（从仓库 README 里的截图也可以看出来，请求到的不只有前 5 条数据），可能你本地的版本是之前的版本，建议更新一下再试试。如果更新后还有问题，欢迎反馈给我，我再检查一下哪里有问题。

**Comment by voidzhakul** [comment]
多谢大佬，换了新版本后问题已解决，之前是直接pip从清华源装的，大概是清华源上的版本太老。
另外建议加个调整请求速度的选项，在服务器跑时上经常因为请求太快被ban掉。
![image](https://user-images.githubusercontent.com/37470928/236457217-6d2c7e2d-2e0b-473a-b3d0-5b6f0eb4cc6d.png)

**Comment by LittleNyima** [comment]
> 多谢大佬，换了新版本后问题已解决，之前是直接pip从清华源装的，大概是清华源上的版本太老。 另外建议加个调整请求速度的选项，在服务器跑时上经常因为请求太快被ban掉。

好的，下个版本会加上请求速度限制。

**Comment by voidzhakul** [comment]
不好意思，重新开一下这个issue
我知道问题出在哪了，和上面说的版本原因无关。

问题原因：**部分链接携带`begin_id`参数**

如图就是一个带有`begin_id`的请求 （出现原因大概是因为向上翻页
![bp](https://user-images.githubusercontent.com/37470928/236464510-1e3411d1-a200-4c29-a9f5-23c9df24d13f.jpg)
 
存在`begin_id`参数时，返回此id上方`size`个抽卡数据
存在`end_id`参数时，返回此id下方`size`个抽卡数据
当两个参数同时存在时，返回数据是他们的交集

但是由于你`end_id`参数是直接拼在后面的，并且不对`begin_id`进行处理，所以当你`end_id`的值在`begin_id`下方时，返回了空数据，程序直接判断当前卡池抽卡记录已经被读完了，但实际并没有。

建议处理URL时判断下`begin_id`,处理一下。
大佬加油hhhh

**Comment by LittleNyima** [comment]
oh，我明白你的意思了。当时开发的时候只测试了用第一页的 URL 请求的情况，没注意到这个参数，我再多试试然后改一下。

**Comment by LittleNyima** [comment]
现在这个问题已经修复，当参数中存在 `begin_id`，在构造 `api_template` 的时候会把这个参数删掉。不过最新的版本没有推送到 pypi，你可以先从源代码安装来解决这个问题。
