### ISSUE TITLE
首次同步数据报错

### ISSUE THREAD

**Issue by hanuxxx** [LittleNyima/honkai-starrail-toolkit#4]
操作步骤：开启游戏查询记录，然后关闭游戏，点击工具箱同步数据

版本为0.5.4

![image](https://github.com/LittleNyima/honkai-starrail-toolkit/assets/23613751/02bb7ae3-0bce-4dc6-8cb7-000b804116be)

**Comment by LittleNyima** [comment]
感谢反馈，我会尽快修复这个问题

**Comment by LittleNyima** [comment]
问题已修复，请更新程序再试
