### ISSUE TITLE
api导入

### ISSUE THREAD

**Issue by Bellaris711** [LittleNyima/honkai-starrail-toolkit#5]
怎么把api导入到抽卡分析工具里面？我在工具界面好像没有看到导入api的入口，教程里面也没有看到方法。可以在教程里面添加一下使用方法吗？

**Comment by Bellaris711** [comment]
此问题已解决，虽然我并不知道技术细节是怎么实现的。不过我又遇到了新的问题，如图：游戏内抽卡记录显示我距离上次抽到五星卡是3抽，上次抽卡距离上上次抽卡是8抽。但是分析工具显示的结果好像不太对。
![image](https://github.com/LittleNyima/honkai-starrail-toolkit/assets/134599778/b56b549e-850a-4f63-b91e-d364bf984e1a)
![image](https://github.com/LittleNyima/honkai-starrail-toolkit/assets/134599778/a5c40e74-e28d-4414-9e00-59fb8afc6e83)
![image](https://github.com/LittleNyima/honkai-starrail-toolkit/assets/134599778/4a5c6253-27ac-468c-be6d-331a785b2e1c)

**Comment by LittleNyima** [comment]
这里的确有点问题，我怀疑是我对十连的处理不是特别对，我最近排查问题改一改
