### ISSUE TITLE
bug反馈？

### ISSUE THREAD

**Issue by Itis-Mei** [LittleNyima/honkai-starrail-toolkit#7]
![93240914b6ea5ad8916a3cde91d09c6](https://github.com/LittleNyima/honkai-starrail-toolkit/assets/112101927/043037f2-2039-4018-8cb7-be70af0a36ac)
第一次用git传issues  不知道图片大佬能不能看到..
我的操作步骤：1：开抽卡分析程序
2：开游戏后打开抽卡页面  打开抽卡记录信息
3：关游戏 同步数据 报错：Traceback (most recent call last):
File "starrail qui common thread.py", line 18in runFile "starrail\quilinterfaces gacha sync.py", line 79, in workValueError: 提取 APIURL失败，遇到的问题: Payload is None, response: null

**Comment by LittleNyima** [comment]
游戏的webcache目录位置变了，所以现在的程序找不到抽卡分析地址。目前已经修复了这个bug，我会尽快重新打包发布，新版本发布之后重新下载就可以了

**Comment by Itis-Mei** [comment]
大佬辛苦


2879602186
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LittleNyima/honkai-starrail-toolkit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月23日(星期天) 凌晨0:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LittleNyima/honkai-starrail-toolkit] bug反馈？ (Issue #7)





 
游戏的webcache目录位置变了，所以现在的程序找不到抽卡分析地址。目前已经修复了这个bug，我会尽快重新打包发布，新版本发布之后重新下载就可以了

**Comment by LittleNyima** [comment]
已发布新版本，请前往 [Release 页面](https://github.com/LittleNyima/honkai-starrail-toolkit/releases/tag/v0.7.4) 或[蓝奏云分流](https://wwmg.lanzouk.com/iwyHh138woih)下载

**Comment by Itis-Mei** [comment]
我又来了 打扰了
![image](https://github.com/LittleNyima/honkai-starrail-toolkit/assets/112101927/763081f8-b204-424d-bd34-fd906945db00)
已经是7.04版本 是不是和之前的问题类似？

**Comment by LittleNyima** [comment]
应该是类似的问题，我今晚更新一下游戏版本看看具体情况

**Comment by LittleNyima** [comment]
@Itis-Mei 实测现在的版本可以正常用，猜测可能和代理有关，可以关掉代理重试一下（之前我发现v2rayN会影响python的一部分功能，不知道是不是因为这个）

**Comment by Itis-Mei** [comment]
关代理可正常使用 感谢


2879602186
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LittleNyima/honkai-starrail-toolkit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月5日(星期六) 凌晨0:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LittleNyima/honkai-starrail-toolkit] bug反馈？ (Issue #7)





 
@Itis-Mei 实测现在的版本可以正常用，猜测可能和代理有关，可以关掉代理重试一下（之前我发现v2rayN会影响python的一部分功能，不知道是不是因为这个）
